# Generated by Django 4.0.1 on 2022-01-23 12:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('time_zone', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(-12), django.core.validators.MaxValueValidator(14)])),
            ],
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='message',
            new_name='message_text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='customer',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='filter_client',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='mailing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alert.mailing'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='message',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alert.client'),
        ),
    ]
